# Form implementation generated from reading ui file 'focus_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FocusWidget(object):
    def setupUi(self, FocusWidget):
        FocusWidget.setObjectName("FocusWidget")
        FocusWidget.resize(580, 486)
        self.focus_plot_widget = PlotWidget(parent=FocusWidget)
        self.focus_plot_widget.setGeometry(QtCore.QRect(20, 30, 531, 321))
        self.focus_plot_widget.setObjectName("focus_plot_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=FocusWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 380, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.f_end = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.f_end.setText("")
        self.f_end.setObjectName("f_end")
        self.gridLayout.addWidget(self.f_end, 1, 1, 1, 1)
        self.f_start = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.f_start.setObjectName("f_start")
        self.gridLayout.addWidget(self.f_start, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.step_size = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.step_size.setText("")
        self.step_size.setObjectName("step_size")
        self.gridLayout.addWidget(self.step_size, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 3)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=FocusWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 380, 91, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_focus_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.start_focus_button.setObjectName("start_focus_button")
        self.verticalLayout.addWidget(self.start_focus_button)
        self.stop_focus_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.stop_focus_button.setObjectName("stop_focus_button")
        self.verticalLayout.addWidget(self.stop_focus_button)
        self.focusing_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.focusing_button.setCheckable(False)
        self.focusing_button.setObjectName("focusing_button")
        self.verticalLayout.addWidget(self.focusing_button)

        self.retranslateUi(FocusWidget)
        QtCore.QMetaObject.connectSlotsByName(FocusWidget)

    def retranslateUi(self, FocusWidget):
        _translate = QtCore.QCoreApplication.translate
        FocusWidget.setWindowTitle(_translate("FocusWidget", "Form"))
        self.label_2.setText(_translate("FocusWidget", "F End"))
        self.label_3.setText(_translate("FocusWidget", "F Step Size"))
        self.label.setText(_translate("FocusWidget", "F Start"))
        self.start_focus_button.setText(_translate("FocusWidget", "Start Focus"))
        self.stop_focus_button.setText(_translate("FocusWidget", "Stop Focus"))
        self.focusing_button.setText(_translate("FocusWidget", "Focusing"))
from pyqtgraph import PlotWidget
